# 文字入力 {#Inputs}

## Font

- [Fonts included with macOS Ventura - Apple Support](https://support.apple.com/en-us/HT213266)
- [Fonts included with macOS Monterey - Apple Support](https://support.apple.com/en-us/HT212587)


### Apple Developer

Apple公式サイトから，いくつかのフォントを無料でダウンロードできる。

- [Fonts for Apple Platforms](https://developer.apple.com/fonts/)
  + San Francisco Pro Fonts
  + San Francisco Compact Fonts
  + San Francisco Mono Fonts
  + San Francisco Arabic Fonts
  + New York Fonts
- [SF Symbols](https://developer.apple.com/sf-symbols/)


### Appleのフォント

- Apple Garamond
- Myriad

[Apple製品のロゴのフォントはMyriad（ミリアド）](http://gajetdaisuke.com/archives/08126_011939.php "http://gajetdaisuke.com/archives/08126_011939.php")


### Googleのフォント

- Catull

[Google社ロゴはどう作られたか](http://wiredvision.jp/news/200803/2008033123.html "http://wiredvision.jp/news/200803/2008033123.html")


## 文字入力

### en dash (–)とem dash (—)の入力方法

macOS

- en dash: ⌥ + -
- em dash: ⌥ + ⇧ + -

Windows

- en dash: Alt + 0150 or Ctrl + テンキーの-
- em dash: Alt + 0151 or Ctrl + Alt + テンキーの-


## 文字化け

メールの文字化けは以下で対応する。

- [文字化けしたメールの修復](https://www.kanzaki.com/docs/jis-recover.html)

添付ファイルにwinmail.datが付いている場合，その中身を確認するためには，そのファイルを変換しなければならない。

- [winmail.dat変換ツール(インストール不要)](http://winmaildat.net/)

ただし，ファイルサイズが大きすぎる場合，変換できないため，[Google検索](https://www.google.com/search?client=safari&rls=en&q=winmail.dat+変換&ie=UTF-8&oe=UTF-8)して，適当なサービスを利用する。
一方，ファイルサイズが小さすぎる場合，ゴミであることがある。

ウェブブラウザの文字化けには，テキストエンコードを変更する必要がある。
どのエンコードにすべきかわからなければ，日本語の中から順番に変えていけばよい。


## Tips

### 隠しファイルを表示する

- ⌘ + ⇧ + .
