# Macの初期設定 {#InitialSetting}


## システム環境設定（macOS Sonoma）

- 一般
    + 「情報」の「コンピュータ名」を変更する。
    + 「共有」の「画面共有」をオンにする。

- トラックパッド
    + 「ポイントとクリック」の「タップでクリック」をオンにする。
    + 「その他のジェスチャ」の「アプリExposé」を「3本指で下にスワイプ」にする。

- ディスプレイとDock
    + 「Dock」の「拡大」を「大」にする。
    + 「Dockを自動的に表示/非表示」をオンにする。
    + 「Mission Control」の「ホットコーナー」の右上を「デスクトップ」にする。
    + 「書類を閉じるときに変更内容を保持するかどうかを確認」をオンにする。

- コントロールセンター
    + 「Bluetooth」を「メニューバーに表示」にする。
    + 「画面ミラーリング」を「メニューバーに常に表示」にする。
    + 「サウンド」を「メニューバーに常に表示」にする。
    + 「聴覚」の「コントロールセンターに表示」にオンにする。
    + 「時計」の「時計のオプション」から，「日付を表示」を「常に」にする。
    + 「時計」の「時計のオプション」から，「秒を表示」をオンにする。

## システム環境設定（古いmacOS）

- 共有
    + 「コンピュータ名」を変更する。
    + 「画面共有」をオンにする。

- トラックパッド
    + 「ポイントとクリック」の「タップでクリック」をオンにする。
    + 「その他のジェスチャ」の「アプリケーションExposé」をオンにする。

- Dockとメニューバー
    + 「Dock」の「拡大」をオンにする。
    + 「Dockを自動的に表示/非表示」をオンにする。
    + 「時計」の「日付を表示」を「常に」にする。
    + 「時計」の「秒を表示」をオンにする。

- Mission Control
    + 「ホットコーナー」の右上を「デスクトップ」にする。

- サウンド
    + 「メニューバーに音量を表示」をオンにする。

- Bluetooth
    + 「メニューバーにBluetoothを表示」をオンにする。

- 一般
    + 「書類を閉じるときに変更内容を保持するかどうかを確認」をオンにする。

- ソフトウェア・アップデート
    + 「詳細」→「新しいアップデートがある場合はダウンロード」をオフにする。


## Finder「環境設定」

- サイドバー
    + 「よく使う項目」のusernameをオンにする。
    + 「場所」のコンピュータ名と「ハードディスク」をオンにする。

- 一般
    + 「新規Finderウインドウで次を表示」を「書類」にする。

- サイドバーにライブラリを追加する。
    + optionを押しながら「移動」をクリックし，「ライブラリ」に移動する。
    + 「ライブラリ」をサイドバーにドラッグ&ドロップする。

- Dockにアプリケーションフォルダを追加する。
    + 「表示形式」を「フォルダ」にする。
    + 「内容の表示形式」を「グリッド」にする。


## テキストエディット「環境設定」

- 新規書類
    + 「フォーマット」を「標準テキスト」にする。
    + 「オプション」の「入力中に自動スペルチェック」「スペルを自動的に修正」「スマート引用符」「スマートダッシュ記号」をオフにする。

- 開く/保存
    + 「HTMLファイルを、フォーマットしたテキストではなくHTMLコードとして表示」をオンにする。


## Safari「環境設定」

- 一般
    + 「ダウンロード後、“安全な”ファイルを開く」をオフにする。

- 詳細
    + 「メニューバーに“開発”メニューを表示」をオンにする。
    + 「Webサイトの完全なアドレスを表示」をオンにする。


## メール「環境設定」

- 表示
    + リストビューで「なし」を選択する。
    + メッセージヘッダを表示で「カスタム」を選択し，以下を追加する。
```
Content-Transfer-Encoding
Content-Type
User-Agent
X-Mailer
charset
```
    + 「メッセージ内のリモートコンテンツを読み込む」をオフにする。
    + 「最新のメッセージを一番上に表示」をオンにする。

- 作成
    + メッセージのフォーマットで「標準テキスト」を選択する。


## メール「よく使う項目に追加」

- 「すべての送信済み」
- 「すべてのゴミ箱」
- 「すべての迷惑メール」
- 「表示」→「お気に入りバーを表示」をオンにする。


## Dockに追加

- ターミナル.app
- アクティビティモニタ.app
- テキストエディット.app
- プレビュー.app
- 辞書.app
- ホーム.app
- ブック.app
- News.app
- /System/Library/CoreServices/Applications/DVD プレイヤー.app
