# Terminalコマンド {#Terminal}

以下のコマンドはmacOS Ventura向けである。
古いmacOSでも使えるものが多いが，細かい点が変わったりしている（デフォルトがbashからzshに変わった）。

- MacBook Proを開いたときに起動しないようにする。
```
$ sudo nvram AutoBoot=%00
```

- MacBook Proを開いたときに起動するようにする（元に戻す）。
```
$ sudo nvram AutoBoot=%03
```

- ZIPファイルから「.DS_Store」と「__MACOSX」を削除する。
    + 単一ファイル
```
$ zip --delete filename.zip "*.DS_Store"
$ zip --delete filename.zip "*__MACOSX*"
```
    + 複数ファイル
```
$ find . -name "*.zip" -exec zip --delete {} "*.DS_Store" \;
$ find . -name "*.zip" -exec zip --delete {} "*__MACOSX*" \;
```

- 不可視ファイルを削除する。
    + 「.DS_Store」を削除する。
```
$ sudo find / -name ".DS_Store" -delete
# ホームディレクトリのみ
$ sudo find ~/ -name ".DS_Store" -delete
```
    + 「.Rapp.history」を削除する。
```
$ sudo find / -name ".Rapp.history" -delete
# ホームディレクトリのみ
$ sudo find ~/ -name ".Rapp.history" -delete
```
    + 「.Rhistory」を削除する。
```
$ sudo find / -name ".Rhistory" -delete
# ホームディレクトリのみ
$ sudo find ~/ -name ".Rhistory" -delete
```

- ファイルの日付を変更する。
```
$ touch -t 202005182400 filename.jpg
```

- PATHを確認する。
```
$ printenv PATH
```
または
```
$ echo $PATH
```

- PATHを通す。
.zshenv（または，~/.bash_profileなど）といったファイルに
```
export PATH=$PATH:追加するPATH
```
という1行を追加する。
追加するたびに1行追加していくのか，追加するPATHに「:」で追加していくのか，どちらが望ましいのかわからない。
追加にはviを使うことができる。

```
$ vi ~/.zshenv

```
次のようにやってもよいはずだが，こうした説明をしているサイトはあまりない。なぜかわからない。

```
echo 'export PATH=$PATH:~/foo/bar' >> ~/.zshenv
```

ファイルを編集したら，
```
$ source ~/.zshenv
```
を実行する。

- 環境変数を確認する。
```
$ export -p
```

ローカルなPATHは
```
$ ls -a ~/
```
のどこかに書かれている。

グローバルなPATHは以下で確認できる。
```
$ cat /etc/paths
$ ls -a /etc/paths.d
```
何かをアンインストールしたときのゴミが残っている場合のみ，該当ファイルを削除してもよいと思う。

- ログインシェルをzshに変更する。
```
$ chsh -s /bin/zsh
```

- ログイン中のユーザーを表示する。
```
$ who
$ w
```

- Macのモデルを確認する。
```
$ sysctl hw.model
```

- Macのアイコンをデスクトップにコピーする。
```
$ cp -r /System/Library/CoreServices/CoreTypes.bundle ~/Desktop/
```

- 喋らせる。
```
$ say -v Kyoko こんにちは
$ say -v 'Kyoko (Enhanced)' こんにちは
$ say -v 'Ava (Premium)' Hello
$ say -v Yuna 안녕하세요
$ say -v Anna Danke schön
# ファイルに保存
$ say -v 'Kyoko (Enhanced)' -o こんにちは.m4a こんにちは
# システム設定 → アクセシビリティ → システムの声 → 声を管理
$ say -v '?'
# 以下は一例
Ava (Premium)       en_US    # Hello, my name is Ava. I am an American-English voice.
Daniel              en_GB    # Hello, my name is Daniel. I am a British-English voice.
Karen               en_AU    # Hello, my name is Karen. I am an Australian-English voice.
Moira               en_IE    # Hello, my name is Moira. I am an Irish-English voice.
Rishi               en_IN    # Hello, my name is Rishi. I am an Indian-English voice.
Samantha            en_US    # Hello, my name is Samantha. I am an American-English voice.
Tessa               en_ZA    # Hello, my name is Tessa. I am a South African-English voice.
```


## macOSのコマンド以外のコマンド

- Google Earth Studioから動画を作成する。
```
$ ffmpeg -r 30 -i Untitled_%03d.jpeg -vcodec libx264 -pix_fmt yuv420p -r 60 GoogleEarth.mp4
```


## 古いmacOS向けコマンド

最新のmacOSでもコマンドが有効かどうかは確認していない。
一部のコマンドは，最新のmacOSで機能しなかったことを確認している。

- スタートアップチャイムを有効にする。
```
$ sudo nvram StartupMute=%00
```

- スタートアップチャイムを無効にする（元に戻す）。
```
$ sudo nvram StartupMute=%01
```

- QuickLookで表示したテキストをコピー可能にする。
```
$ defaults write com.apple.finder QLEnableTextSelection -bool TRUE; killall Finder
```

- Pantherで日本語を表示させる。

「ターミナル」→「ウィンドウ設定...」で「ターミナルインスペクタ」を開く。

→「エミュレーション」

「非 ASCII 文字をエスケープする」のチェックをはずす。

→「ディスプレイ」

「ワイドグリフは 2 桁とカウントする」にチェックする。
「設定をデフォルトとして使用」をクリックする。

```
$ ls -v
```

日本語を入力する
```
$ vi ~/.inputrc
```
以下を記述する。

set convert-meta off
set output-meta on
set input-meta on
