# Software {#Software}

macOSで有益なソフトウェアのリストです。
研究で使用するものを主に取り上げています。

## Software {#Software}

- 必須
  + [Airtime](https://www.airtimetools.com/)
    + [mmhmm](https://www.mmhmm.app/) の後継
  + [Amphetamine](https://apps.apple.com/jp/app/amphetamine/id937984704)
  + [ATOK](https://atok.com/)
  + [Camo](https://reincubate.com/camo/)
  + [ChatGPT](https://openai.com/chatgpt)
  + [Discord](https://discord.com/)
  + [Dropbox](https://www.dropbox.com/)
    - [Dropboxインストーラーの直リン](https://www.dropbox.com/downloading?type=full)
  + [EBMac](http://www31.ocn.ne.jp/~h_ishida/MacOS/Mac.html)
  + ~~[FileMaker Pro](http://www.filemaker.co.jp/products/filemaker.html)~~
  + [Gestimer 2](https://apps.apple.com/jp/app/gestimer-2/id6447125648)
    - [Gestimer](https://apps.apple.com/us/app/gestimer-for-those-little/id990588172) の後継
  + [Google Earth](http://www.google.co.jp/intl/ja/earth/)
  + [HandBrake](https://handbrake.fr/)
  + [Homebrew](https://brew.sh/)
  + [Ice](https://github.com/jordanbaird/Ice)
    - [Bartender](https://www.macbartender.com/) の代替
    - [Hidden Bar](https://apps.apple.com/jp/app/hidden-bar/id1452453066) の代替
  + [Little Snitch](https://www.obdev.at/products/littlesnitch/)
  + [LosslessCut](https://github.com/mifi/lossless-cut)
  + [Luna Display](https://astropad.com/product/lunadisplay/)
  + [Mapture](https://apps.apple.com/app/mapture/id1671995907)
  + [NotchNook](https://lo.cafe/notchnook)
  + [OBS Studio](https://obsproject.com/)
  + [OmniFocus](https://itunes.apple.com/jp/app/omnifocus/id402835630)
  + [OmniGraffle](https://www.omnigroup.com/omnigraffle)
  + [OmniOutliner](https://www.omnigroup.com/omnioutliner)
  + [OwlOCR](https://apps.apple.com/jp/app/owlocr/id6462355119)
  + [PopClip](https://pilotmoon.com/popclip/)
    - [PopClip Extensions](http://pilotmoon.com/popclip/extensions/)
    - [GitHub - takeshinishimura/PopClip-Extensions](https://github.com/takeshinishimura/PopClip-Extensions)
    - [GitHub - hirakujira/ChatGPT-Grammar-Check-PopClip-Extension](https://github.com/hirakujira/ChatGPT-Grammar-Check-PopClip-Extension)
  + [Positron](https://github.com/posit-dev/positron)
  + [Pure Paste](https://sindresorhus.com/pure-paste)
  + [R](https://cran.r-project.org/)
  + [RStudio](https://www.rstudio.com/)
  + [Scapple](https://apps.apple.com/jp/app/scapple/id568020055)
  + [Scrivener](https://itunes.apple.com/jp/app/scrivener/id418889511)
  + [SiteSucker](https://itunes.apple.com/jp/app/sitesucker/id442168834)
  + [TeamViewer](https://www.teamviewer.com/ja/)
  + [TeXShop](https://pages.uoregon.edu/koch/texshop/)
  + [TextExpander](https://textexpander.com/)
  + [Visual Studio Code](https://code.visualstudio.com/)
    - Pathを通す → [Configure the path with VS Code](https://code.visualstudio.com/docs/setup/mac#_configure-the-path-with-vs-code) 
  + [VLC media player](https://www.videolan.org/vlc/)
  + [VMware Fusion](http://www.vmware.com/products/fusion/overview.html)
  + [Whisper Transcription](https://apps.apple.com/jp/app/whisper-transcription/id1668083311)
  + [Zotero](https://www.zotero.org/)
    - [Papers](http://www.mekentosj.com/papers/) の代替
    - Source Folder for Attaching New Files: ~/Dropbox/Zotero
    - Location of Files: ~/Dropbox/Zotero
    - Use subfolder defined by "/%T/%w/%y"
    - Renaming Format: Format for all Types except Patents: "{%a }{(%y) }{%t}"
    - Add suffix when authors are omitted " et al."

- 開発終了したため困っている
  + ~~[HoudahGPS](https://www.houdah.com/houdahGPS/)~~
  + [SlidePilot](https://slidepilotapp.com/en/)
  + [Pro Mouse](https://apps.apple.com/jp/app/pro-mouse/id1505869474)

## フォント {#fonts}

- [Font Awesome](https://fontawesome.com/)
  + [Font Awesome 5](https://fontawesome.com/v5/download) #TeXで使うなら
  + [CTAN: Package fontawesome5](https://www.ctan.org/pkg/fontawesome5) #TeXで使うなら
- [Source Han Serif / 源ノ明朝](https://github.com/adobe-fonts/source-han-serif)
- [Source Han Sans / 源ノ角ゴシック](https://github.com/adobe-fonts/source-han-sans)
- [Source Han Mono / 源ノ等幅](https://github.com/adobe-fonts/source-han-mono)
- [Noto Serif](https://fonts.google.com/noto/specimen/Noto+Serif)
- [Noto Sans](https://fonts.google.com/noto/specimen/Noto+Sans)
- [Morisawa BIZ UDMincho](https://github.com/googlefonts/morisawa-biz-ud-mincho/)
- [Morisawa BIZ UDGothic](https://github.com/googlefonts/morisawa-biz-ud-gothic/)
- [Morisawa Desktop Manager](https://morisawafonts.com/mypage/dm/)
- [IBM Plex Sans JP](https://github.com/IBM/plex)
- [機械彫刻用標準書体フォント](https://font.kim/)


## Touch Bar

- [EnergyBar: Supercharge your Mac's Touch Bar.](https://github.com/billziss-gh/EnergyBar)
- [pac-bar: Pac-Man for the MacBook Pro Touch Bar](https://github.com/henryefranks/pac-bar)
- [touchbar_nyancat: Stupid nyancat animation on your +$2k MacBook Pro's Touchbar](https://github.com/avatsaev/touchbar_nyancat)
- [Touch Bar Piano](https://www.utsire.com/touch-bar-piano/)
- [TouchSwitcher app switcher for Touch Bar](https://hazeover.com/touchswitcher.html)
- [The Original Quick Launcher for Touch Bar](http://julianthayn.com/rocket)
- [TouchSwitcher app switcher for Touch Bar](https://hazeover.com/touchswitcher.html)


## その他（メモ） {#others}

- [macOS Sierra (10.12) で Photoshop CS6 / Illustrator CS6 を使う](https://doratex.hatenablog.jp/entry/20160921/1474401468)
- [EBView](http://ebview.sourceforge.net/home-ja.html)
- [UNIXで電子辞書をしゃぶりつくそう](http://hp.vector.co.jp/authors/VA000022/unixdic/)
- [対訳君＆CheckAlignユーザーズサイト](http://www.mcl-corp.jp/usersite/us_index.htm)
- [Free FLV Player for Windows](http://flv-player.us/index_mdv.php)
- [CPUID](https://www.cpuid.com/index.php)
- [名作フリーソフトを訪ねて](https://xtech.nikkei.com/it/pc/article/special/20081024/1009118/)
- [“一芸”オンラインソフト](https://xtech.nikkei.com/it/pc/article/NPC/20071108/286796/)
- [DVD 関連のフリーソフト](https://www.gigafree.net/media/ripping/)

Mac OS X 10.4 (Tiger) に標準で登録されているDashboard WidgetのWeatherでは，「City, Sate or ZIP Code:」の欄でreturnキーを押さなければ接続されない。
